site_name: ${{values.component_id | dump}}
site_description: ${{values.description | dump}}

nav:
  - Introduction: index.md
  - Architecture: architecture.md
  - Development: development.md
  - Linting: linting.md
  - Naming-cheatsheet: naming-cheatsheet.md

plugins:
  - techdocs-core